#!/usr/bin/env node

/**
 * build.js
 *
 * Spawns xterms to build all of the docker containers generated by debian.js
 *
 * Used for sweeping tests after making changes to the generators.
 */

// Dependencies
var spawn = require('child_process').spawn
var path  = require('path')
var dists = require('./debian_dists.js')
var fs = require('fs')

for(dist in dists) {
  for(release in dists[dist]) {
    for(project in dists[dist][release]) {
      for(version in dists[dist][release][project]) {
        (function scope(dist,release,project,version) {
          var dir = path.join(__dirname,dist,release,project,version)
          var file = path.join(dir,'output')
          var command = "docker"
          var args = ["build","--no-cache","."]
          console.log(args)
          var file = fs.createWriteStream(file)
          var child = spawn(command,args,{cwd:dir})
          child.on('error',function(e) {
            console.log(e)
          })
          child.stdout.pipe(file)
          child.stderr.pipe(file)
          console.log("Spawned: "+dir)
        })(dist,release,project,version)
      }
    }
  }
}
