FROM fedora:20
MAINTAINER William Blankenship <wblankenship@nodesource.com>

RUN yum install -y \
      automake \
      libicu \
      curl \
      gcc \
      gcc-c++ \
      git \
      kernel-devel \
      make \
      perl \
      which \
 && yum clean all

